[profile.default]
src = "src"
out = "out"
libs = ["lib"]
revert_strings = "debug"

# Define RPC aliases:
[rpc_endpoints]
arbitrum_mainnet = "${RPC_MAINNET}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

# Custom additions:
# - revert_strings: injects strings for compiler-generated internal reverts (and require) reason strings.
# - arbitrum_mainnet: used for testing the UniswapExchange contract.
